# Generated by Django 4.2.10 on 2025-07-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_location_participantcost_printingcost_sessioncost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Diredawa', 'Diredawa'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Central Ethiopia', 'Central Ethiopia'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Sidama', 'Sidama'), ('Somali', 'Somali'), ('South Ethiopia', 'South Ethiopia'), ('Southwest', 'Southwest'), ('Tigray', 'Tigray')], max_length=255),
        ),
    ]
