# Generated by Django 4.2.10 on 2025-07-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_location_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airtransport',
            old_name='round_trip_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='airtransport',
            name='single_trip_price',
        ),
        migrations.AddField(
            model_name='airtransport',
            name='trip_type',
            field=models.CharField(choices=[('SINGLE', 'Single Trip'), ('ROUND', 'Round Trip')], default='SINGLE', max_length=10),
        ),
    ]
