# Generated by Django 4.2.10 on 2025-07-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_round_trip_price_airtransport_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtransport',
            name='trip_type',
        ),
    ]
