# Generated by Django 4.2.10 on 2025-07-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_procurementitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainactivity',
            name='target_type',
            field=models.CharField(choices=[('cumulative', 'Cumulative'), ('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('constant', 'Constant')], default='cumulative', max_length=20),
        ),
        migrations.AlterField(
            model_name='performancemeasure',
            name='target_type',
            field=models.CharField(choices=[('cumulative', 'Cumulative'), ('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('constant', 'Constant')], default='cumulative', max_length=20),
        ),
    ]
