# Generated by Django 4.2.10 on 2025-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_mainactivity_target_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='objectives_data',
            field=models.JSONField(blank=True, help_text='Comprehensive objectives data for multi-objective plans', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='selected_objectives_count',
            field=models.IntegerField(default=1, help_text='Number of objectives selected for this plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='total_objectives_weight',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Total weight of all selected objectives', max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('LEAD_EXECUTIVE', 'Lead Executive'), ('TEAM_DESK', 'Team/Desk'), ('INDIVIDUAL', 'Individual')], max_length=20),
        ),
    ]
