# Generated by Django 4.2.10 on 2025-07-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_plan_objectives_data_plan_selected_objectives_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='objectives_data',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='selected_objectives_count',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='total_objectives_weight',
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('LEO/EO Plan', 'LEO/EO Plan'), ('Desk/Team Plan', 'Desk/Team Plan'), ('Individual Plan ', 'Individual Plan ')], max_length=20),
        ),
    ]
