# Generated by Django 4.2.10 on 2025-07-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_remove_plan_objectives_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='selected_objectives_data',
            field=models.JSONField(blank=True, help_text='Complete data of all selected objectives with initiatives, measures, and activities', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('LEAD_EXECUTIVE', 'Lead Executive'), ('TEAM_DESK', 'Team/Desk'), ('INDIVIDUAL', 'Individual')], max_length=20),
        ),
    ]
