# Generated by Django 4.2.10 on 2025-07-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_plan_selected_objectives_data_alter_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='selected_objectives_data',
        ),
    ]
