# Generated by Django 4.2.10 on 2025-07-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_remove_plan_selected_objectives_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('LEO/EO Plan', 'LEO/EO Plan'), ('Desk/Team Plan', 'Desk/Team Plan'), ('Individual Plan ', 'Individual Plan ')], max_length=20),
        ),
    ]
