# Generated by Django 4.2.10 on 2025-07-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_plan_selected_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativefeed',
            name='strategic_objective',
            field=models.ForeignKey(blank=True, help_text='The strategic objective this initiative feed belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_feeds', to='organizations.strategicobjective'),
        ),
    ]
