# Generated by Django 4.2.10 on 2025-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_detailactivity_teamdeskplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdeskplan',
            name='detail_activities',
        ),
        migrations.RemoveField(
            model_name='teamdeskplan',
            name='initiatives',
        ),
        migrations.RemoveField(
            model_name='teamdeskplan',
            name='leo_eo_plan',
        ),
        migrations.RemoveField(
            model_name='teamdeskplan',
            name='main_activities',
        ),
        migrations.RemoveField(
            model_name='teamdeskplan',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='teamdeskplan',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='teamdeskplan',
            name='performance_measures',
        ),
        migrations.RemoveField(
            model_name='teamdeskplan',
            name='team_desk',
        ),
        migrations.RemoveField(
            model_name='teamdeskplanreview',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='teamdeskplanreview',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PLANNER', 'Planner'), ('EVALUATOR', 'Evaluator')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DetailActivity',
        ),
        migrations.DeleteModel(
            name='TeamDeskPlan',
        ),
        migrations.DeleteModel(
            name='TeamDeskPlanReview',
        ),
    ]
