# Generated by Django 4.2.10 on 2025-08-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_remove_teamdeskplan_detail_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainactivity',
            name='annual_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='q1_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q1 Target (Jul-Sep)'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='q2_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q2 Target (Oct-Dec)'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='q3_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q3 Target (Jan-Mar)'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='q4_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q4 Target (Apr-Jun)'),
        ),
        migrations.AlterField(
            model_name='performancemeasure',
            name='annual_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='performancemeasure',
            name='q1_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q1 Target (Jul-Sep)'),
        ),
        migrations.AlterField(
            model_name='performancemeasure',
            name='q2_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q2 Target (Oct-Dec)'),
        ),
        migrations.AlterField(
            model_name='performancemeasure',
            name='q3_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q3 Target (Jan-Mar)'),
        ),
        migrations.AlterField(
            model_name='performancemeasure',
            name='q4_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q4 Target (Apr-Jun)'),
        ),
    ]
