# Generated by Django 4.2.10 on 2025-08-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_alter_mainactivity_annual_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='selected_objectives_weights',
            field=models.JSONField(blank=True, help_text='Custom weights assigned by planner for each selected objective {objective_id: weight}', null=True),
        ),
    ]
